cmake_minimum_required(VERSION 4.0)
project(proyectofinal20252_el_gran_torneo_de_la_arena_proyecto_manuelr_lupim)

set(CMAKE_CXX_STANDARD 20)

add_executable(proyectofinal20252_el_gran_torneo_de_la_arena_proyecto_manuelr_lupim main.cpp
        src/Personaje.cpp
        src/Personaje.h
        src/ObjetoMagico.cpp
        src/ObjetoMagico.h
        src/Inventario.cpp
        src/Inventario.h
        src/Guild.cpp
        src/Guild.h
        src/Arena.cpp
        src/Arena.h
        src/Heroe.cpp
        src/Heroe.h
        src/Guerrero.cpp
        src/Guerrero.h
        src/Mago.cpp
        src/Mago.h
        src/Sanador.cpp
        src/Sanador.h
        src/Berserker.cpp
        src/Berserker.h
        src/Lupasos.cpp
        src/Lupasos.h)
