#ifndef PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_PROYECTO_MANUELR_LUPIM_DAGASOMBRIA_H
#define PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_PROYECTO_MANUELR_LUPIM_DAGASOMBRIA_H


#include "ObjetoMagico.h"

class DagaSombria : public ObjetoMagico {
public:
    DagaSombria(int stock);
    void usar(Personaje* objetivo) override;
};

#endif //PROYECTOFINAL20252_EL_GRAN_TORNEO_DE_LA_ARENA_PROYECTO_MANUELR_LUPIM_DAGASOMBRIA_H